# Basic Makefile

# Compilers and options
CC=gcc
CPPFLAGS= `pkg-config --cflags gtk+-2.0`
CFLAGS= -std=c99 -O2
LDFLAGS=
LDLIBS= `pkg-config --libs gtk+-2.0`


# Cleaning rule
clean:
	rm -f *.o *~
# END
