# Basic Makefile
 
# Compilers and options
CC=clang
CPPFLAGS=
CFLAGS= -Wall -Wextra -pedantic -std=c99 -O2
LDFLAGS=
LDLIBS=

# Cleaning rule
clean:
	rm -f *.o *~
	rm -f print_string
	rm -f string_len
	rm -f mystrncpy
# END
